<a href="https://colab.research.google.com/github/hiraasif854-eng/python-project/blob/main/Numpy_Practice_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Name = Hira Asif
# Roll number = 898414

In [1]:
# Task 1:
import numpy as np
values = np.array([10, 20, 30, 40, 50])
# Sum:
print(np.sum(values))
# Average:
print(np.mean(values))
# Maximum:
print(np.max(values))
# Minimum:
print(np.min(values))


150
30.0
50
10


In [2]:
# Task 2:
values = np.array([45, 80, 30, 90, 55, 20])
Greater_values = values[values >= 50]
print(Greater_values)

[80 90 55]


In [5]:
# Task 3:
numbers = np.array([1, 2, 3, 4, 5, 6])
new_array = numbers.reshape(2,3)
print(new_array)

[[1 2 3]
 [4 5 6]]


In [4]:
# Task 4:
values = np.random.randint(40,100,10)
print(values)

[47 52 40 72 97 96 84 48 54 52]


In [3]:
# Task 5:
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])
passed = marks[marks >= 50]
print(passed)
failed = marks[marks < 50]
print(failed)
print(len(passed))
print(len(failed))

[67 89 90 70 58]
[35 45 22]
5
3


In [ ]:
# Creating Numpy arrays
# One dimensional array
import numpy as np
numbers = np.array([10,20,30,40])
print(numbers)
# Two dimensional array
marks = np.array([
    [70,80,90],
    [60,75,85],
    [88,92,95]

])
print(marks)


[10 20 30 40]
[[70 80 90]
 [60 75 85]
 [88 92 95]]


In [ ]:
# important array properties
#1) ndim
import numpy as np
data = np.array([
    [10,20,30],
    [40,50,60]
])
print(data.ndim)

2


In [ ]:
# 2) shape
# shape tells us the number of rows and columns
import numpy as np
data = np.array([
    [10,20,30],
    [40,50,60]
])
print(data.shape)

(2, 3)


In [ ]:
# 3) size
# size tells us the total number of values
data = np.array([
    [10,20,30],
    [40,50,60]
])
print(data.size)

6


In [ ]:
# 4) dtype:
# dtype tells us the data type
import numpy as np
data = np.array([
    [10,20,30],
    [40,50,60]
])
print(data.dtype)

int64


In [ ]:
# 5) Indexing
# indexing means getting one specific value from an array
# indexing starts from 0
import numpy as np
numbers = np.array([10,20,30,40,50])
print(numbers[0])
print(numbers[3])
print(numbers[2])
print(numbers[1])
print(numbers[4])
# negative index
print(numbers[-1])

10
40
30
20
50
50


In [ ]:
# 6) indexing in a 2D array
marks = np.array([
    [70,80,90],
    [60,75,85]
])
print(marks[0 , 1])
print(marks[1,2])

80
85


In [ ]:
# 7) Slicing
# slicing means getting multiple values from an array
numbers = np.array([10,20,30,40,50])
print(numbers[1:4]) # the pattern is [start : stop]
print(numbers[1:3]) # the start value is included, stop value not included

[20 30 40]
[20 30]


In [ ]:
# 8) Vectorized operations
# important features of numpy
# NumPy can perform one operation on all values at the same time
numbers = np.array([10,20,30,40,50])
# ADD
print(numbers + 5)
# MULTIPLY
print(numbers * 5)
# SUBTRACT
print(numbers - 5)
# DIVIDE
print(numbers / 2)
# This is called a vectorized operation.
# We do not need to use a loop for every value.

[15 25 35 45 55]
[ 50 100 150 200 250]
[ 5 15 25 35 45]
[ 5. 10. 15. 20. 25.]


In [ ]:
# 9) Operations between two arrays
# We can also perform operations between two arrays
a = np.array([10,20,30])
b = np.array([1,2,3])
# ADDITION
print(a + b)
# MULTIPLICATION
print(a * b)
# this is called as an element wise operation

[11 22 33]
[10 40 90]


In [ ]:
# 10) Mathematical functions:
# Square Root:
numbers = np.array([4,9,16,25])
print(np.sqrt(numbers))
# Power:
numbers = np.array([2,3,4])
print(np.power(numbers , 2))
# Absolute Value:
numbers = np.array([-10,-5,4,8]) # gives positive value
print(np.abs(numbers))
# Round:
numbers = np.array([4.2 , 5.7 , 8.9])
print(np.round(numbers))


[2. 3. 4. 5.]
[ 4  9 16]
[10  5  4  8]
[4. 6. 9.]


In [ ]:
# 11) Aggregration Functions
# Aggregration function gives us summary values
marks = np.array([70,85,60,95,80])
# SUM
print(np.sum(marks))
# AVERAGE:
print(np.mean(marks))
# MAXIMUM VALUE:
print(np.max(marks))
# MINIMUM VALUE:
print(np.min(marks))
# MEDIAN:
print(np.median(marks)) # first arrange in asecnding to descending order,
# then finding middle value
# STANDARD DEVIATION: tells us how spread out the values are
print(np.std(marks))

390
78.0
95
60
80.0
12.083045973594572


In [ ]:
# 12) Conditions in NumPy:
# We can apply conditions directly to NumPy arrays.
marks = np.array([30, 50, 80, 45, 90, 20])
print(marks >= 50)

[False  True  True False  True False]


In [ ]:
# 13) Filtering Data:
# We can also get only the values that match a condition.
marks = np.array([30, 50, 80, 45, 90, 20])
passed = marks[marks >= 50]
print(passed)
# To get failed marks:
failed = marks[marks < 50]
print(failed)




[50 80 90]
[30 45 20]


In [ ]:
# 14) Reshape:
# reshape() changes the structure of an array
numbers = np.array([1, 2, 3, 4, 5, 6])
new_array = numbers.reshape(2,3)
print(new_array)
#Important rule:
# The total number of values must stay the same.
# 2 × 3 = 6
# So the reshape is possible.

[[1 2 3]
 [4 5 6]]


In [ ]:
# 15. Flatten
# flatten() changes a multi-dimensional array into a one-dimensional array.
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(data.flatten())

In [ ]:
# 16. Useful NumPy Functions
# zeros()
# Creates an array with zero values
print(np.zeros(5))
# ones()
# Creates an array with one values.
print(np.ones(5))
# arange()
#Creates a range of numbers.
print(np.arange(1,11))
# using a step:
print(np.arange(0,11,2))# [start, stop, step]

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [ ]:
# 17) Random Numbers
#NumPy can also generate random numbers.
marks = np.random.randint(40, 100, 10)# start 40 k kahin say bhi start hoga 100 tk khtm or 10 he values hongi
print(marks)

[68 73 71 95 43 97 60 98 43 92]
